#! /bin/bash
set -o nounset
set -o errexit
##set -o xtrace

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

CLONE_SELDON_SERVER="git clone -q  https://github.com/SeldonIO/seldon-server.git"

if [[ $# < 1 ]]; then
  echo "Needs API version"
  exit 1
fi
VERSION=$1

SELDON_SERVER_TAG=tags/${VERSION}

cd ${STARTUP_DIR}
rm -rf seldon-server* seldon-server*.war
echo 'cloning seldon-server project from github'
$CLONE_SELDON_SERVER
cd ${STARTUP_DIR}/seldon-server
echo "using version[${SELDON_SERVER_TAG}]"
git checkout ${SELDON_SERVER_TAG} &> /dev/null
cd ${STARTUP_DIR}/seldon-server/server
echo 'building seldon-server project'
mvn package -DskipTests -q
cp target/seldon-server*.war ${STARTUP_DIR}/
cd ${STARTUP_DIR}

WAR_FILE=`ls seldon-server*.war`
rm -rf ./webapps

mkdir -p ./webapps/ROOT

unzip -qx -d ./webapps/ROOT/ ${WAR_FILE} &> /dev/null

# clear up
rm -rf seldon-server* seldon-server*.war
echo 'done'

