dummy:
	@echo dummy

.PHONY: save_images
save_images:
	@./save_images

.PHONY: load_images
load_images:
	@./load_images

clean:
	@echo "--- cleaning imagetars ---"
	@rm -fv images/*.gz
	@rm -fv images/*.tar

