dummy:
	@echo dummy

status:
	vagrant global-status

list_boxes:
	vagrant box list

start_env:
	vagrant up

stop_env:
	vagrant halt

destroy_env:
	vagrant destroy -f

connect_ssh:
	vagrant ssh

remove_box:
	vagrant box remove seldontestvm || echo ok
	vagrant box list

