#!/bin/bash
set -o nounset
set -o errexit

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

IMAGES_DIR=${STARTUP_DIR}/images

source ${STARTUP_DIR}/images_list.sh

#archive dist dir
DIST_DIR_FPATH=${STARTUP_DIR}/../../../dist
TAR_FILE="dist.tar"
if [ ! -f "${IMAGES_DIR}/${TAR_FILE}.gz" ]; then
    tar cvf ${IMAGES_DIR}/${TAR_FILE} \
        --exclude=local_mysql_data \
        --exclude=local-logs \
        --exclude=local-models \
        --exclude=local_zookeeper_data \
        --exclude=run_settings \
        --exclude=movie_recommender_demo/raw_data \
        --exclude=movie_recommender_demo/seldon_data \
        -C `dirname ${DIST_DIR_FPATH}`  `basename ${DIST_DIR_FPATH}`
    gzip -v ${IMAGES_DIR}/${TAR_FILE}
else
    echo "SKIPPING ${IMAGES_DIR}/${TAR_FILE}.gz"
fi

for i in "${IMAGES_LIST[@]}"
do
    FPATH="${IMAGES_DIR}/$i.tar"
    if [ ! -f "${FPATH}" ]; then
        echo "saving $FPATH"
        docker save --output="$FPATH" $i
    else
        echo "SKIPPING $FPATH"
    fi
done

