#!/bin/bash

set -o nounset
set -o errexit

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"
PROJ_DIR=${STARTUP_DIR}/../..

FILENAME=movielens_demo
TAR_FILE="${FILENAME}.tar"
GZ_FILE=${TAR_FILE}.gz
RESOURCES_DIR=${PROJ_DIR}/dist/resources

setup_resource() {
    mkdir -pv ${RESOURCES_DIR}
    rm -fv ${RESOURCES_DIR}/${GZ_FILE}
    cp -v ${GZ_FILE} ${RESOURCES_DIR}/${GZ_FILE}
}

cd ${STARTUP_DIR}
setup_resource

