#!/bin/bash
set -o nounset
set -o errexit

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"
PROJ_DIR=${STARTUP_DIR}/..
[ -f ${PROJ_DIR}/build_settings ] && source ${PROJ_DIR}/build_settings

BUILD_START_TIME=$(date)

build_images() {
    for i in "${IMAGES_LIST[@]}"; do
        echo "--- building $i ---"
        cd "${STARTUP_DIR}/$i"
        make build_image SELDON_VERSION=0.2
    done
}

declare -a IMAGES_LIST=( \
    "java7jre_image" \
    "tomcat7_image" \
    "zookeeper_image" \
    "api_server_image" \
    "api_server_demo_image" \
    "api_server_data_logs_image" \
    "seldon-models" \
    "mysql_image" \
    "mysql_data" \
    "memcache_image" \
    "td_agent_image" \
    "spark_image" \
    "seldon-tools" \
    "consul_image" \
    "movielens_data_transform" \
)

BUILD_EXCLUDED_IMAGES=${BUILD_EXCLUDED_IMAGES:-}
if [ ! -z ${BUILD_EXCLUDED_IMAGES} ]; then
    for i in "${BUILD_EXCLUDED_IMAGES[@]}"; do
        echo "Removing [${i}] from build"
        IMAGES_LIST=( ${IMAGES_LIST[@]/$i} )
    done
fi

if [ "${#IMAGES_LIST[@]}" -gt 0 ];then
    build_images
fi

BUILD_END_TIME=$(date)

echo "--- build finished ---"
echo "--- start: ${BUILD_START_TIME} ---"
echo "---   end: ${BUILD_END_TIME} ---"

