#!/bin/bash
set -o nounset
set -o errexit

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"
PROJ_DIR=${STARTUP_DIR}/..
[ -f ${PROJ_DIR}/build_settings ] && source ${PROJ_DIR}/build_settings

clean_images() {
    for i in "${IMAGES_LIST[@]}"; do
        echo "--- cleaning $i ---"
        cd "${STARTUP_DIR}/$i"
        make clean
    done
}

declare -a IMAGES_LIST=( \
    "mysql_image" \
    "mysql_data" \
    "spark_image" \
    "api_server_image" \
    "seldon-models" \
    "api_server_demo_image" \
    "movielens_data_transform" \
)

BUILD_EXCLUDED_IMAGES=${BUILD_EXCLUDED_IMAGES:-}
if [ ! -z ${BUILD_EXCLUDED_IMAGES} ];then
    for i in "${BUILD_EXCLUDED_IMAGES[@]}"; do
        echo "Removing [${i}] from build"
        IMAGES_LIST=( ${IMAGES_LIST[@]/$i} )
    done
fi

if [ "${#IMAGES_LIST[@]}" -gt 0 ];then
    clean_images
fi

